spring:
  datasource:
    # 默认给我们配置的数据源为 : class com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/zea-user?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    # 可以使用 spring.datasource.type 指定自定义的数据源类型，值为 要使用的连接池实现的完全限定名。
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #Spring Boot 默认是不注入这些属性值的，需要自己绑定
      #druid 数据源专有配置
      initialSize: 5 # 初始化大小
      minIdle: 5 # 最小
      maxActive: 20 # 最大
      maxWait: 60000 # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: SELECT 'x' # 连接测试sql
      testWhileIdle: true # 当连接空闲时，是否执行连接测试
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false
      filters: config,wall,stat,log4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙

#开启日志
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml # mapper.xml文件存放位置
  configuration:
    map-underscore-to-camel-case: true # 驼峰装换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    admin: # 调度中心 nacos服务
      addresses:
        #xxljob调度中心部署  例如：http://127.0.0.1:8080/xxl-job-admin,多个配置逗号分隔 "http://address01,http://address02"
        http://127.0.0.1:10210/xxl-job-admin
    accessToken: default_token_zea_cloud #调度中心通讯TOKEN [选填]：非空时启用
    executor:
      #xxljob配置的执行器名称，和http://127.0.0.1:10210/xxl-job-admin 那边配置一样的名称，不然注册不上去
      appName: zea-admin-service
      ip: 127.0.0.1 #执行器IP，默认为空表示自动获取IP
      port: 9999 #xxljob配置的端口号，默认为9999
      logPath: logs/xxl-job/jobhandler/admin-service  #执行器运行日志文件存储磁盘路径
      logRetentionDays: 30 #调度中心日志表数据保存天数，过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能


